general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock the session
listener {
    timeout = 300 # 5 min
    on-timeout = loginctl lock-session
}

# Turn the screen off shortly after locking
listener {
    timeout = 330 # 5.5 min
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# Suspend after a longer idle period
listener {
    timeout = 1200 # 20 min
    on-timeout = systemctl suspend
}
